import type { Product, Artisan, Order, User } from './types';

export const users: User[] = [
  {
    id: 'artisan-1',
    email: 'riya.sharma@example.com',
    role: 'artisan',
    createdAt: '2023-01-10T10:00:00Z',
    lastLogin: '2023-11-01T12:30:00Z',
  },
  {
    id: 'artisan-2',
    email: 'aarav.patel@example.com',
    role: 'artisan',
    createdAt: '2023-02-15T11:00:00Z',
    lastLogin: '2023-10-30T18:00:00Z',
  },
  {
    id: 'user-123',
    email: 'buyer1@example.com',
    role: 'buyer',
    createdAt: '2023-03-20T14:00:00Z',
    lastLogin: '2023-11-01T20:00:00Z',
  },
];

export const artisans: Artisan[] = [
  {
    id: 'artisan-1',
    name: 'Riya Sharma',
    shopName: 'Riya\'s Creations',
    bio: 'Creating beautiful handcrafted pottery from the heart of Rajasthan.',
    profilePicture: 'https://picsum.photos/seed/artisan1/100/100',
    location: 'Jaipur, India',
    story: 'From a young age, I was fascinated by the pottery wheels in my village. I spent years learning from the masters, and now I blend those traditional techniques with my own modern aesthetic. Each piece tells a story of the earth, my hands, and a centuries-old tradition.',
    contactEmail: 'support@riyascreations.com',
    socialLinks: {
      instagram: 'https://instagram.com/riyascreations',
      facebook: 'https://facebook.com/riyascreations',
    },
    createdAt: '2023-01-10T10:00:00Z',
    updatedAt: '2023-10-25T09:00:00Z',
  },
  {
    id: 'artisan-2',
    name: 'Aarav Patel',
    shopName: 'Woven Dreams',
    bio: 'Specializing in handwoven textiles and tapestries, blending modern designs with age-old techniques.',
    profilePicture: 'https://picsum.photos/seed/artisan2/100/100',
    location: 'Kutch, India',
    story: 'Weaving is in my family\'s blood. I learned the art of the loom from my grandmother, and I am passionate about keeping this beautiful craft alive. I source my materials locally and use natural dyes to create textiles that are both beautiful and sustainable.',
    socialLinks: {
      twitter: 'https://twitter.com/wovendreams',
    },
    createdAt: '2023-02-15T11:00:00Z',
    updatedAt: '2023-10-28T14:20:00Z',
  },
];

export const products: Product[] = [
  {
    id: 'prod-1',
    artisanId: 'artisan-1',
    name: 'Azure Ceramic Vase',
    description: 'A stunning handcrafted ceramic vase, glazed in a deep azure blue. Perfect as a centerpiece or for holding your favorite flowers. Its unique shape is inspired by the waves of the ocean.',
    tagline: 'Hand-thrown by artisans in Jaipur.',
    price: 3750,
    currency: 'INR',
    category: 'Home Decor',
    stock: 15,
    images: [
      'https://images.unsplash.com/photo-1597696929736-6d13bed8e6a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjZXJhbWljJTIwdmFzZXxlbnwwfHx8fDE3NTg0NDM0ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://picsum.photos/seed/prod1-2/600/600',
      'https://picsum.photos/seed/prod1-3/600/600',
    ],
    shippingInfo: 'Ships within 3-5 business days.',
    aiInsights: {
        keyFeatures: ['Hand-thrown pottery', 'Lead-free glaze', 'Unique azure color'],
        styleTags: ['Minimalist', 'Coastal', 'Modern'],
        useCases: ['Flower arrangement', 'Statement decor piece', 'Bookshelf styling'],
    },
    isActive: true,
    status: 'active', // Legacy
    createdAt: '2023-05-01T10:00:00Z',
    updatedAt: '2023-10-20T11:00:00Z',
  },
  {
    id: 'prod-2',
    artisanId: 'artisan-2',
    name: 'Sunset Tapestry',
    description: 'A large, handwoven wall tapestry depicting a vibrant sunset over the desert. Made with naturally dyed wool and cotton fibers.',
    tagline: 'Woven with dreams in the heart of Kutch.',
    price: 9900,
    currency: 'INR',
    category: 'Textiles',
    stock: 5,
    images: [
      'https://images.unsplash.com/photo-1562869929-bda0650edb1f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxM3x8dGFwZXN0cnl8ZW58MHx8fHwxNzU4NDQzNTA2fDA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://picsum.photos/seed/prod2-2/600/600',
    ],
    shippingInfo: 'Made to order. Ships within 1-2 weeks.',
     aiInsights: {
        keyFeatures: ['100% natural fibers', 'Handwoven on a traditional loom', 'Rich, warm color palette'],
        styleTags: ['Bohemian', 'Rustic', 'Eclectic'],
        useCases: ['Living room wall art', 'Above a bed headboard', 'Meditation space focus'],
    },
    isActive: true,
    status: 'active', // Legacy
    createdAt: '2023-06-15T14:30:00Z',
    updatedAt: '2023-10-22T18:00:00Z',
  },
  {
    id: 'prod-3',
    name: 'Earthenware Mug Set',
    artisanId: 'artisan-1',
    description: 'Set of two rustic earthenware mugs, perfect for your morning coffee or tea. The textured finish provides a comfortable, earthy grip.',
    tagline: 'Sip your morning brew from the earth itself.',
    price: 2500,
    currency: 'INR',
    stock: 25,
    category: 'Kitchenware',
    images: ['https://images.unsplash.com/photo-1708368952731-db40e6a86d21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxNHx8ZWFydGhlbndhcmUlMjBtdWclMjBzZXR8ZW58MHx8fHwxNzU4NDQzOTM0fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    isActive: true,
    status: 'active', // Legacy
    createdAt: '2023-07-01T09:00:00Z',
    updatedAt: '2023-09-30T10:00:00Z',
  },
  {
    id: 'prod-4',
    name: 'Geometric Print Scarf',
    artisanId: 'artisan-2',
    description: 'A lightweight cotton scarf with a hand-block printed geometric pattern. Versatile and stylish for any season.',
    tagline: 'A touch of modern artistry, block-printed by hand.',
    price: 2000,
    currency: 'INR',
    stock: 50,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1609803384370-0e73ef8d424f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxnZW9tZXRyaWMlMjBwcmludCUyMHNjYXJmfGVufDB8fHx8MTc1ODQ0NDA2M3ww&ixlib=rb-4.1.0&q=80&w=1080'],
    isActive: true,
    status: 'active', // Legacy
    createdAt: '2023-07-20T18:00:00Z',
    updatedAt: '2023-10-15T12:00:00Z',
  },
  {
    id: 'prod-5',
    name: 'Terracotta Planter',
    artisanId: 'artisan-1',
    description: 'A simple yet elegant terracotta planter with a subtle etched pattern. Includes a drainage hole and matching saucer.',
    tagline: 'Give your favorite plant a worthy home.',
    price: 2300,
    currency: 'INR',
    stock: 0,
    category: 'Gardening',
    images: ['https://images.unsplash.com/photo-1728463098232-4ab2f94f53f2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxOXx8dGVycmFjb3R0YSUyMHBsYW50ZXJ8ZW58MHx8fHwxNzU4NDQ0MjcxfDA&ixlib=rb-4.1.0&q=80&w=1080'],
    isActive: false,
    status: 'archived', // Legacy
    createdAt: '2023-08-10T11:45:00Z',
    updatedAt: '2023-10-25T16:00:00Z',
  },
  {
    id: 'prod-6',
    artisanId: 'artisan-1',
    name: 'Glazed Soup Bowls',
    description: 'Set of four ceramic soup bowls with a unique reactive glaze. Each bowl has a slightly different pattern, making them one-of-a-kind.',
    tagline: 'Serve your favorite soups in style.',
    price: 4200,
    currency: 'INR',
    category: 'Kitchenware',
    stock: 12,
    images: ['https://images.unsplash.com/photo-1648889095175-1757165415e5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxN3x8Z2xhemVkJTIwc291cCUyMGJvd2xzfGVufDB8fHx8MTc1ODQ0NTAzNHww&ixlib=rb-4.1.0&q=80&w=1080'],
    isActive: true,
    status: 'active',
    createdAt: '2023-09-01T10:00:00Z',
    updatedAt: '2023-10-20T11:00:00Z',
  },
  {
    id: 'prod-7',
    artisanId: 'artisan-2',
    name: 'Embroidered Cushion Cover',
    description: 'A vibrant, hand-embroidered cushion cover from Kutch. Features traditional mirror work and colorful thread.',
    tagline: 'Add a pop of color and culture to your home.',
    price: 3200,
    currency: 'INR',
    category: 'Textiles',
    stock: 20,
    images: ['https://images.unsplash.com/photo-1689413182146-14b0a9b972b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxN3x8ZW1icm9pZGVyZWQlMjBjdXNoaW9ufGVufDB8fHx8MTc1ODQ0NDc3Mnww&ixlib=rb-4.1.0&q=80&w=1080'],
    isActive: true,
    status: 'active',
    createdAt: '2023-09-15T14:30:00Z',
    updatedAt: '2023-10-22T18:00:00Z',
  },
  {
    id: 'prod-8',
    name: 'Ceramic Tea Set',
    artisanId: 'artisan-1',
    description: 'A complete tea set for two, including a teapot, two cups, and a serving tray. Finished with a delicate crackle glaze.',
    tagline: 'For moments of shared tranquility.',
    price: 6800,
    currency: 'INR',
    category: 'Kitchenware',
    stock: 8,
    images: ['https://images.unsplash.com/photo-1721373489867-b95a7b3fe16c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjZXJhbWljJTIwdGVhJTIwc2V0fGVufDB8fHx8MTc1ODQ0Mzc5MHww&ixlib=rb-4.1.0&q=80&w=1080'],
    isActive: true,
    status: 'active',
    createdAt: '2023-10-01T09:00:00Z',
    updatedAt: '2023-10-30T10:00:00Z',
  },
    {
    id: 'prod-9',
    name: 'Hand-painted Wooden Box',
    artisanId: 'artisan-1',
    description: 'A small wooden box, hand-painted with intricate floral motifs. Perfect for storing jewelry or keepsakes.',
    tagline: 'A beautiful home for your little treasures.',
    price: 1800,
    currency: 'INR',
    stock: 30,
    category: 'Home Decor',
    images: ['https://picsum.photos/seed/prod9-1/600/600'],
    isActive: true,
    status: 'active',
    createdAt: '2023-10-10T18:00:00Z',
    updatedAt: '2023-10-25T12:00:00Z',
  },
  {
    id: 'prod-10',
    name: 'Natural Dye Table Runner',
    artisanId: 'artisan-2',
    description: 'A beautiful table runner made from handwoven cotton and colored with natural, plant-based dyes.',
    tagline: 'Dress your table in the colors of nature.',
    price: 2900,
    currency: 'INR',
    stock: 18,
    category: 'Textiles',
    images: ['https://images.unsplash.com/photo-1591011094220-0d66c676a6f7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8bmF0dXJhbCUyMGR5ZSUyMHRhYmxlJTIwcnVubmVyfGVufDB8fHx8MTc1ODQ0NTI1NHww&ixlib=rb-4.1.0&q=80&w=1080'],
    isActive: true,
    status: 'active',
    createdAt: '2023-10-12T11:45:00Z',
    updatedAt: '2023-10-28T16:00:00Z',
  },
  {
    id: 'prod-11',
    name: 'Silver Jhumka Earrings',
    artisanId: 'artisan-1',
    description: 'Traditional silver jhumka earrings with delicate filigree work. Lightweight and perfect for any occasion.',
    tagline: 'Timeless elegance for your ears.',
    price: 4500,
    currency: 'INR',
    stock: 22,
    category: 'Jewelry',
    images: ['https://images.unsplash.com/photo-1663170808179-06942aa40a56?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxzaWx2ZXIlMjBqaHVta2ElMjBlYXJyaW5nc3xlbnwwfHx8fDE3NTg0NDQ0ODN8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    isActive: true,
    status: 'active',
    createdAt: '2023-10-15T10:00:00Z',
    updatedAt: '2023-10-29T11:00:00Z',
  },
  {
    id: 'prod-12',
    name: 'Block-Printed Quilt',
    artisanId: 'artisan-2',
    description: 'A soft, breathable cotton quilt featuring a classic Rajasthani block-print pattern. Reversible design.',
    tagline: 'Wrap yourself in the comfort of tradition.',
    price: 8500,
    currency: 'INR',
    stock: 7,
    category: 'Textiles',
    images: ['https://picsum.photos/seed/prod12-1/600/600'],
    isActive: true,
    status: 'active',
    createdAt: '2023-10-18T14:30:00Z',
    updatedAt: '2023-10-30T18:00:00Z',
  },
];

export const orders: Order[] = [
  {
    id: 'ord-001',
    buyerId: 'user-123',
    artisanId: 'artisan-1',
    items: [{ productId: 'prod-1', productName: 'Azure Ceramic Vase', quantity: 1, unitPrice: 3750, itemImageUrl: 'https://picsum.photos/seed/prod1-1/600/600' }],
    totalAmount: 3750,
    shippingAddress: {
        fullName: "Alice Johnson",
        addressLine1: "123 Market St",
        city: "San Francisco",
        state: "CA",
        zipCode: "94103",
        country: "USA",
    },
    status: 'Delivered',
    paymentStatus: 'Paid',
    orderDate: '2023-10-15T10:30:00Z',
    updatedAt: '2023-10-20T15:00:00Z',
  },
  {
    id: 'ord-002',
    buyerId: 'user-456',
    artisanId: 'artisan-1',
    items: [
      { productId: 'prod-3', productName: 'Earthenware Mug Set', quantity: 1, unitPrice: 2500, itemImageUrl: 'https://picsum.photos/seed/prod3-1/600/600' },
      { productId: 'prod-4', productName: 'Geometric Print Scarf', quantity: 1, unitPrice: 2000, itemImageUrl: 'https://picsum.photos/seed/prod4-1/600/600' },
    ],
    totalAmount: 4500,
    shippingAddress: {
        fullName: "Bob Williams",
        addressLine1: "456 Oak Ave",
        city: "Chicago",
        state: "IL",
        zipCode: "60607",
        country: "USA"
    },
    status: 'Shipped',
    paymentStatus: 'Paid',
    orderDate: '2023-10-28T11:00:00Z',
    updatedAt: '2023-10-29T18:00:00Z',
  },
  {
    id: 'ord-003',
    buyerId: 'user-789',
    artisanId: 'artisan-2',
    items: [{ productId: 'prod-2', productName: 'Sunset Tapestry', quantity: 1, unitPrice: 9900, itemImageUrl: 'https://picsum.photos/seed/prod2-1/600/600' }],
    totalAmount: 9900,
    shippingAddress: {
        fullName: "Charlie Brown",
        addressLine1: "789 Pine Ln",
        city: "New York",
        state: "NY",
        zipCode: "10001",
        country: "USA"
    },
    status: 'Pending',
    paymentStatus: 'Pending Payment',
    orderDate: '2023-11-01T12:00:00Z',
    updatedAt: '2023-11-01T12:00:00Z',
  },
    {
    id: 'ord-004',
    buyerId: 'user-123',
    artisanId: 'artisan-2',
    items: [{ productId: 'prod-7', productName: 'Embroidered Cushion Cover', quantity: 2, unitPrice: 3200, itemImageUrl: 'https://images.unsplash.com/photo-1689413182146-14b0a9b972b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxN3x8ZW1icm9pZGVyZWQlMjBjdXNoaW9ufGVufDB8fHx8MTc1ODQ0NDc3Mnww&ixlib=rb-4.1.0&q=80&w=1080' }],
    totalAmount: 6400,
    shippingAddress: {
        fullName: "Alice Johnson",
        addressLine1: "123 Market St",
        city: "San Francisco",
        state: "CA",
        zipCode: "94103",
        country: "USA",
    },
    status: 'Processing',
    paymentStatus: 'Paid',
    orderDate: '2023-11-02T14:00:00Z',
    updatedAt: '2023-11-02T14:00:00Z',
  },
  {
    id: 'ord-005',
    buyerId: 'user-456',
    artisanId: 'artisan-1',
    items: [{ productId: 'prod-8', productName: 'Ceramic Tea Set', quantity: 1, unitPrice: 6800, itemImageUrl: 'https://picsum.photos/seed/prod8-1/600/600' }],
    totalAmount: 6800,
    shippingAddress: {
        fullName: "Bob Williams",
        addressLine1: "456 Oak Ave",
        city: "Chicago",
        state: "IL",
        zipCode: "60607",
        country: "USA"
    },
    status: 'Pending',
    paymentStatus: 'Pending Payment',
    orderDate: '2023-11-03T09:30:00Z',
    updatedAt: '2023-11-03T09:30:00Z',
  }
];

export const categories: string[] = [
  'Home Decor',
  'Textiles',
  'Kitchenware',
  'Accessories',
  'Gardening',
  'Jewelry',
  'Painting',
];

    
    
    
