import type { Product, Artisan, Order, User } from './types';

export const users: User[] = [
  {
    id: 'artisan-1',
    email: 'riya.sharma@example.com',
    role: 'artisan',
    createdAt: '2023-01-10T10:00:00Z',
    lastLogin: '2023-11-01T12:30:00Z',
    cart: [],
  },
  {
    id: 'artisan-2',
    email: 'aarav.patel@example.com',
    role: 'artisan',
    createdAt: '2023-02-15T11:00:00Z',
    lastLogin: '2023-10-30T18:00:00Z',
    cart: [],
  },
  {
    id: 'user-123',
    email: 'buyer1@example.com',
    role: 'buyer',
    createdAt: '2023-03-20T14:00:00Z',
    lastLogin: '2023-11-01T20:00:00Z',
    cart: [],
  },
];

export const artisans: Artisan[] = [
  {
    id: 'artisan-1',
    name: 'Riya Sharma',
    shopName: 'Riya\'s Creations',
    bio: 'Creating beautiful handcrafted pottery from the heart of Rajasthan.',
    profilePicture: 'https://picsum.photos/seed/artisan1/100/100',
    location: 'Jaipur, India',
    story: 'From a young age, I was fascinated by the pottery wheels in my village. I spent years learning from the masters, and now I blend those traditional techniques with my own modern aesthetic. Each piece tells a story of the earth, my hands, and a centuries-old tradition.',
    contactEmail: 'support@riyascreations.com',
    socialLinks: {
      instagram: 'https://instagram.com/riyascreations',
      facebook: 'https://facebook.com/riyascreations',
    },
    createdAt: '2023-01-10T10:00:00Z',
    updatedAt: '2023-10-25T09:00:00Z',
  },
  {
    id: 'artisan-2',
    name: 'Aarav Patel',
    shopName: 'Woven Dreams',
    bio: 'Specializing in handwoven textiles and tapestries, blending modern designs with age-old techniques.',
    profilePicture: 'https://picsum.photos/seed/artisan2/100/100',
    location: 'Kutch, India',
    story: 'Weaving is in my family\'s blood. I learned the art of the loom from my grandmother, and I am passionate about keeping this beautiful craft alive. I source my materials locally and use natural dyes to create textiles that are both beautiful and sustainable.',
    socialLinks: {
      twitter: 'https://twitter.com/wovendreams',
    },
    createdAt: '2023-02-15T11:00:00Z',
    updatedAt: '2023-10-28T14:20:00Z',
  },
  {
    id: 'artisan-3',
    name: 'Arjun Verma',
    shopName: 'Heritage Crafts UP',
    bio: 'Bringing you the finest crafts from the heart of Uttar Pradesh. From the gleaming brass of Moradabad to the delicate glass of Firozabad.',
    profilePicture: 'https://picsum.photos/seed/artisan3/100/100',
    location: 'Uttar Pradesh, India',
    story: 'I grew up watching the masters work in the narrow lanes of Varanasi and Agra. My mission is to give these diverse art forms a global platform.',
    contactEmail: 'contact@heritageup.com',
    socialLinks: {
      instagram: 'https://instagram.com/heritageup',
    },
    createdAt: '2023-11-01T09:00:00Z',
    updatedAt: '2023-11-01T09:00:00Z',
  },
];

export const products: Product[] = [
  {
    id: 'prod-1',
    artisanId: 'artisan-1',
    name: 'Azure Ceramic Vase',
    description: 'A stunning handcrafted ceramic vase, glazed in a deep azure blue. Perfect as a centerpiece or for holding your favorite flowers. Its unique shape is inspired by the waves of the ocean.',
    tagline: 'Hand-thrown by artisans in Jaipur.',
    price: 3750,
    currency: 'INR',
    category: 'Home Decor',
    stock: 15,
    images: [
      'https://images.unsplash.com/photo-1597696929736-6d13bed8e6a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjZXJhbWljJTIwdmFzZXxlbnwwfHx8fDE3NTg0NDM0ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://picsum.photos/seed/prod1-2/600/600',
      'https://picsum.photos/seed/prod1-3/600/600',
    ],
    shippingInfo: 'Ships within 3-5 business days.',
    aiInsights: {
      keyFeatures: ['Hand-thrown pottery', 'Lead-free glaze', 'Unique azure color'],
      styleTags: ['Minimalist', 'Coastal', 'Modern'],
      useCases: ['Flower arrangement', 'Statement decor piece', 'Bookshelf styling'],
    },
    region: 'Rajasthan',
    artisanName: 'Riya Sharma',
    isActive: true,
    status: 'active', // Legacy
    createdAt: '2023-05-01T10:00:00Z',
    updatedAt: '2023-10-20T11:00:00Z',
  },
  {
    id: 'prod-2',
    artisanId: 'artisan-2',
    name: 'Sunset Tapestry',
    description: 'A large, handwoven wall tapestry depicting a vibrant sunset over the desert. Made with naturally dyed wool and cotton fibers.',
    tagline: 'Woven with dreams in the heart of Kutch.',
    price: 9900,
    currency: 'INR',
    category: 'Textiles',
    stock: 5,
    images: [
      'https://images.unsplash.com/photo-1562869929-bda0650edb1f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxM3x8dGFwZXN0cnl8ZW58MHx8fHwxNzU4NDQzNTA2fDA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://picsum.photos/seed/prod2-2/600/600',
    ],
    shippingInfo: 'Made to order. Ships within 1-2 weeks.',
    aiInsights: {
      keyFeatures: ['100% natural fibers', 'Handwoven on a traditional loom', 'Rich, warm color palette'],
      styleTags: ['Bohemian', 'Rustic', 'Eclectic'],
      useCases: ['Living room wall art', 'Above a bed headboard', 'Meditation space focus'],
    },
    region: 'Gujarat',
    artisanName: 'Aarav Patel',
    isActive: true,
    status: 'active', // Legacy
    createdAt: '2023-06-15T14:30:00Z',
    updatedAt: '2023-10-22T18:00:00Z',
  },
  {
    id: 'prod-3',
    name: 'Earthenware Mug Set',
    artisanId: 'artisan-1',
    description: 'Set of two rustic earthenware mugs, perfect for your morning coffee or tea. The textured finish provides a comfortable, earthy grip.',
    tagline: 'Sip your morning brew from the earth itself.',
    price: 2500,
    currency: 'INR',
    stock: 25,
    category: 'Kitchenware',
    images: ['https://images.unsplash.com/photo-1708368952731-db40e6a86d21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxNHx8ZWFydGhlbndhcmUlMjBtdWclMjBzZXR8ZW58MHx8fHwxNzU4NDQzOTM0fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    region: 'Rajasthan',
    artisanName: 'Riya Sharma',
    isActive: true,
    status: 'active', // Legacy
    createdAt: '2023-07-01T09:00:00Z',
    updatedAt: '2023-09-30T10:00:00Z',
  },
  {
    id: 'prod-4',
    name: 'Geometric Print Scarf',
    artisanId: 'artisan-2',
    description: 'A lightweight cotton scarf with a hand-block printed geometric pattern. Versatile and stylish for any season.',
    tagline: 'A touch of modern artistry, block-printed by hand.',
    price: 2000,
    currency: 'INR',
    stock: 50,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1609803384370-0e73ef8d424f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxnZW9tZXRyaWMlMjBwcmludCUyMHNjYXJmfGVufDB8fHx8MTc1ODQ0NDA2M3ww&ixlib=rb-4.1.0&q=80&w=1080'],
    region: 'Gujarat',
    artisanName: 'Aarav Patel',
    isActive: true,
    status: 'active', // Legacy
    createdAt: '2023-07-20T18:00:00Z',
    updatedAt: '2023-10-15T12:00:00Z',
  },
  {
    id: 'prod-5',
    name: 'Terracotta Planter',
    artisanId: 'artisan-1',
    description: 'A simple yet elegant terracotta planter with a subtle etched pattern. Includes a drainage hole and matching saucer.',
    tagline: 'Give your favorite plant a worthy home.',
    price: 2300,
    currency: 'INR',
    stock: 0,
    category: 'Gardening',
    images: ['https://images.unsplash.com/photo-1728463098232-4ab2f94f53f2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxOXx8dGVycmFjb3R0YSUyMHBsYW50ZXJ8ZW58MHx8fHwxNzU4NDQ0MjcxfDA&ixlib=rb-4.1.0&q=80&w=1080'],
    region: 'Rajasthan',
    artisanName: 'Riya Sharma',
    isActive: false,
    status: 'archived', // Legacy
    createdAt: '2023-08-10T11:45:00Z',
    updatedAt: '2023-10-25T16:00:00Z',
  },
  {
    id: 'prod-6',
    artisanId: 'artisan-1',
    name: 'Glazed Soup Bowls',
    description: 'Set of four ceramic soup bowls with a unique reactive glaze. Each bowl has a slightly different pattern, making them one-of-a-kind.',
    tagline: 'Serve your favorite soups in style.',
    price: 4200,
    currency: 'INR',
    category: 'Kitchenware',
    stock: 12,
    images: ['https://images.unsplash.com/photo-1648889095175-1757165415e5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxN3x8Z2xhemVkJTIwc291cCUyMGJvd2xzfGVufDB8fHx8MTc1ODQ0NTAzNHww&ixlib=rb-4.1.0&q=80&w=1080'],
    region: 'Rajasthan',
    artisanName: 'Riya Sharma',
    isActive: true,
    status: 'active',
    createdAt: '2023-09-01T10:00:00Z',
    updatedAt: '2023-10-20T11:00:00Z',
  },
  {
    id: 'prod-7',
    artisanId: 'artisan-2',
    name: 'Embroidered Cushion Cover',
    description: 'A vibrant, hand-embroidered cushion cover from Kutch. Features traditional mirror work and colorful thread.',
    tagline: 'Add a pop of color and culture to your home.',
    price: 3200,
    currency: 'INR',
    category: 'Textiles',
    stock: 20,
    images: ['https://images.unsplash.com/photo-1689413182146-14b0a9b972b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxN3x8ZW1icm9pZGVyZWQlMjBjdXNoaW9ufGVufDB8fHx8MTc1ODQ0NDc3Mnww&ixlib=rb-4.1.0&q=80&w=1080'],
    region: 'Gujarat',
    artisanName: 'Aarav Patel',
    isActive: true,
    status: 'active',
    createdAt: '2023-09-15T14:30:00Z',
    updatedAt: '2023-10-22T18:00:00Z',
  },
  {
    id: 'prod-8',
    name: 'Ceramic Tea Set',
    artisanId: 'artisan-1',
    description: 'A complete tea set for two, including a teapot, two cups, and a serving tray. Finished with a delicate crackle glaze.',
    tagline: 'For moments of shared tranquility.',
    price: 6800,
    currency: 'INR',
    category: 'Kitchenware',
    stock: 8,
    images: ['https://images.unsplash.com/photo-1721373489867-b95a7b3fe16c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjZXJhbWljJTIwdGVhJTIwc2V0fGVufDB8fHx8MTc1ODQ0Mzc5MHww&ixlib=rb-4.1.0&q=80&w=1080'],
    region: 'Rajasthan',
    artisanName: 'Riya Sharma',
    isActive: true,
    status: 'active',
    createdAt: '2023-10-01T09:00:00Z',
    updatedAt: '2023-10-30T10:00:00Z',
  },
  {
    id: 'prod-9',
    name: 'Hand-painted Wooden Box',
    artisanId: 'artisan-1',
    description: 'A small wooden box, hand-painted with intricate floral motifs. Perfect for storing jewelry or keepsakes.',
    tagline: 'A beautiful home for your little treasures.',
    price: 1800,
    currency: 'INR',
    stock: 30,
    category: 'Home Decor',
    images: ['https://images.unsplash.com/photo-1614623171216-7755e8650e8e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxoYW5kJTIwcGFpbnRlZCUyMHdvb2RlbiUyMGJveHxlbnwwfHx8fDE3NTg0NDUxNTl8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    region: 'Rajasthan',
    artisanName: 'Riya Sharma',
    isActive: true,
    status: 'active',
    createdAt: '2023-10-10T18:00:00Z',
    updatedAt: '2023-10-25T12:00:00Z',
  },
  {
    id: 'prod-10',
    name: 'Natural Dye Table Runner',
    artisanId: 'artisan-2',
    description: 'A beautiful table runner made from handwoven cotton and colored with natural, plant-based dyes.',
    tagline: 'Dress your table in the colors of nature.',
    price: 2900,
    currency: 'INR',
    stock: 18,
    category: 'Textiles',
    images: ['https://images.unsplash.com/photo-1591011094220-0d66c676a6f7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8bmF0dXJhbCUyMGR5ZSUyMHRhYmxlJTIwcnVubmVyfGVufDB8fHx8MTc1ODQ0NTI1NHww&ixlib=rb-4.1.0&q=80&w=1080'],
    region: 'Gujarat',
    artisanName: 'Aarav Patel',
    isActive: true,
    status: 'active',
    createdAt: '2023-10-12T11:45:00Z',
    updatedAt: '2023-10-28T16:00:00Z',
  },
  {
    id: 'prod-11',
    name: 'Silver Jhumka Earrings',
    artisanId: 'artisan-1',
    description: 'Traditional silver jhumka earrings with delicate filigree work. Lightweight and perfect for any occasion.',
    tagline: 'Timeless elegance for your ears.',
    price: 4500,
    currency: 'INR',
    stock: 22,
    category: 'Jewelry',
    images: ['https://images.unsplash.com/photo-1663170808179-06942aa40a56?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxzaWx2ZXIlMjBqaHVta2ElMjBlYXJyaW5nc3xlbnwwfHx8fDE3NTg0NDQ0ODN8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    region: 'Rajasthan',
    artisanName: 'Riya Sharma',
    isActive: true,
    status: 'active',
    createdAt: '2023-10-15T10:00:00Z',
    updatedAt: '2023-10-29T11:00:00Z',
  },
  {
    id: 'prod-12',
    name: 'Block-Printed Quilt',
    artisanId: 'artisan-2',
    description: 'A soft, breathable cotton quilt featuring a classic Rajasthani block-print pattern. Reversible design.',
    tagline: 'Wrap yourself in the comfort of tradition.',
    price: 8500,
    currency: 'INR',
    stock: 7,
    category: 'Textiles',
    images: ['https://images.unsplash.com/photo-1700530501759-189d3dbfe2d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8YmxvY2slMjBwcmludGVkJTIwcXVpbHR8ZW58MHx8fHwxNzU4NDQ1ODIwfDA&ixlib=rb-4.1.0&q=80&w=1080'],
    region: 'Gujarat',
    artisanName: 'Aarav Patel',
    isActive: true,
    status: 'active',
    createdAt: '2023-10-18T14:30:00Z',
    updatedAt: '2023-10-30T18:00:00Z',
  },
  {
    id: 'prod-13',
    name: 'Agra Marble Inlay Plate',
    artisanId: 'artisan-3',
    description: 'Taj Mahal-style stone inlay artistry (Pietra Dura). This handcrafted marble plate features intricate floral patterns inlaid with semi-precious stones, a craft perfected in Agra.',
    tagline: 'A piece of the Taj Mahal in your home.',
    price: 12500,
    currency: 'INR',
    category: 'Home Decor',
    stock: 8,
    images: ['/images/products/marble-inlay.jpg'], // Local image
    isActive: true,
    status: 'active',
    createdAt: '2023-11-10T10:00:00Z',
    updatedAt: '2023-11-10T10:00:00Z',
    region: 'Uttar Pradesh',
    artisanName: 'Arjun Verma',
    aiInsights: {
      keyFeatures: ['White Marble', 'Semi-precious stone inlay', 'Handcrafted'],
      styleTags: ['Mughal', 'Luxurious', 'Traditional'],
      useCases: ['Wall Decor', 'Table Centerpiece', 'Premium Gift'],
    },
  },
  {
    id: 'prod-14',
    name: 'Moradabad Brass Ganesh Idol',
    artisanId: 'artisan-3',
    description: 'Exquisite brass idol from the Brass City of India, Moradabad. This meticulously crafted Ganesh statue brings a golden glow of tradition to your home.',
    tagline: 'Divine craftsmanship in brass.',
    price: 3500,
    currency: 'INR',
    category: 'Home Decor',
    stock: 15,
    images: ['/images/products/brassware.jpg'], // Local image
    isActive: true,
    status: 'active',
    createdAt: '2023-11-11T12:00:00Z',
    updatedAt: '2023-11-11T12:00:00Z',
    region: 'Uttar Pradesh',
    artisanName: 'Arjun Verma',
    aiInsights: {
      keyFeatures: ['Solid Brass', 'Hand Polished', 'Intricate Detail'],
      styleTags: ['Religious', 'Traditional', 'Antique'],
      useCases: ['Worship', 'Home Decor', 'Housewarming Gift'],
    },
  },
  {
    id: 'prod-15',
    name: 'Aligarh Antique Padlock',
    artisanId: 'artisan-3',
    description: 'A robust and decorative antique-style padlock from Aligarh, known globally for its quality locks. Fully functional with a unique key mechanism.',
    tagline: 'Security with a touch of history.',
    price: 1800,
    currency: 'INR',
    category: 'Home Decor',
    stock: 25,
    images: ['/images/products/aligarh-lock.jpg'], // Local image
    isActive: true,
    status: 'active',
    createdAt: '2023-11-12T09:30:00Z',
    updatedAt: '2023-11-12T09:30:00Z',
    region: 'Uttar Pradesh',
    artisanName: 'Arjun Verma',
    aiInsights: {
      keyFeatures: ['Heavy-duty metal', 'Working mechanism', 'Vintage finish'],
      styleTags: ['Industrial', 'Vintage', 'Rustic'],
      useCases: ['Collectible', 'Functional Lock', 'Decorative Paperweight'],
    },
  },
  {
    id: 'prod-16',
    name: 'Gorakhpur Terracotta Horse',
    artisanId: 'artisan-3',
    description: 'UNESCO-recognized terracotta artistry from Gorakhpur. This large, ornate horse statue is handmade from natural clay and fired to perfection.',
    tagline: 'The spirit of the earth, captured in clay.',
    price: 4200,
    currency: 'INR',
    category: 'Home Decor',
    stock: 5,
    images: ['/images/products/terracotta-horse.jpg'], // Local image
    isActive: true,
    status: 'active',
    createdAt: '2023-11-13T14:15:00Z',
    updatedAt: '2023-11-13T14:15:00Z',
    region: 'Uttar Pradesh',
    artisanName: 'Arjun Verma',
    aiInsights: {
      keyFeatures: ['Natural Clay', 'Hand-sculpted', 'Kiln-fired'],
      styleTags: ['Folk Art', 'Rustic', 'Indian Village'],
      useCases: ['Garden Decor', 'Living Room Statement', 'Cultural Gift'],
    },
  },
  {
    id: 'prod-17',
    name: 'Firozabad Glass Bangle Set',
    artisanId: 'artisan-3',
    description: 'A dazzling set of glass bangles from Firozabad, the glass capital of India. Features intricate hand-painted designs and vibrant colors.',
    tagline: 'Vibrant colors, delicate sound.',
    price: 950,
    currency: 'INR',
    category: 'Jewelry',
    stock: 50,
    images: ['/images/products/glass-bangles.jpg'], // Local image
    isActive: true,
    status: 'active',
    createdAt: '2023-11-14T11:00:00Z',
    updatedAt: '2023-11-14T11:00:00Z',
    region: 'Uttar Pradesh',
    artisanName: 'Arjun Verma',
    aiInsights: {
      keyFeatures: ['Glass work', 'Hand-painted', 'Set of 12'],
      styleTags: ['Ethnic', 'Colorful', 'Festive'],
      useCases: ['Wedding Wear', 'Daily Wear', 'Cultural Events'],
    },
  },
  {
    id: 'prod-18',
    name: 'Mathura Sanjhi Art Stencil',
    artisanId: 'artisan-3',
    description: 'Delicate hand-cut paper stencils of Radha-Krishna from Mathura. A traditional temple art form that creates intricate patterns on water or floors.',
    tagline: 'Intricate paper artistry devoted to Lord Krishna.',
    price: 1200,
    currency: 'INR',
    category: 'Painting',
    stock: 10,
    images: ['/images/products/sanjhi-art.jpg'], // Local image
    isActive: true,
    status: 'active',
    createdAt: '2023-11-15T10:00:00Z',
    updatedAt: '2023-11-15T10:00:00Z',
    region: 'Uttar Pradesh',
    artisanName: 'Arjun Verma',
    aiInsights: {
      keyFeatures: ['Hand-cut paper', 'Temple Art', 'Intricate Stencil'],
      styleTags: ['Devotional', 'Traditional', 'Folk Art'],
      useCases: ['Rangoli Stencil', 'Framed Art', 'Cultural Gift'],
    },
  },
  {
    id: 'prod-19',
    name: 'Khairabad Blue Pottery Vase',
    artisanId: 'artisan-3',
    description: 'Stunning blue-glazed pottery from Khairabad, Sitapur. This vase is fired at low temperatures and features Persian-influenced floral designs.',
    tagline: 'The mesmerizing blue of Sitapur.',
    price: 2800,
    currency: 'INR',
    category: 'Home Decor',
    stock: 12,
    images: ['/images/products/blue-pottery.jpg'], // Local image
    isActive: true,
    status: 'active',
    createdAt: '2023-11-16T11:00:00Z',
    updatedAt: '2023-11-16T11:00:00Z',
    region: 'Uttar Pradesh',
    artisanName: 'Arjun Verma',
    aiInsights: {
      keyFeatures: ['Blue Glaze', 'Quartz Stone Dough', 'Hand-painted'],
      styleTags: ['Persian-style', 'Vibrant', 'Artistic'],
      useCases: ['Flower Vase', 'Home Accent', 'Decorative Piece'],
    },
  },
  {
    id: 'prod-20',
    name: 'Lucknowi Chikankari Fabric',
    artisanId: 'artisan-3',
    description: 'The most refined hand embroidery in the world from Lucknow. Detailed thread work on fine fabric, featuring the famous "shadow work".',
    tagline: 'Elegance woven in white thread.',
    price: 4500,
    currency: 'INR',
    category: 'Textiles',
    stock: 20,
    images: ['/images/products/chikankari.jpg'], // Local image
    isActive: true,
    status: 'active',
    createdAt: '2023-11-17T14:30:00Z',
    updatedAt: '2023-11-17T14:30:00Z',
    region: 'Uttar Pradesh',
    artisanName: 'Arjun Verma',
    aiInsights: {
      keyFeatures: ['Hand Embroidery', 'White-on-White', 'Fine Muslin/Georgette'],
      styleTags: ['Elegant', 'Sophisticated', 'Summer Wear'],
      useCases: ['Kurta Material', 'Dupatta', 'Designer Wear'],
    },
  },
  {
    id: 'prod-21',
    name: 'Saharanpur Hand-Carved Box',
    artisanId: 'artisan-3',
    description: 'Export-quality carved wooden box from Saharanpur. Expertly crafted from Sheesham wood with intricate floral jaali (lattice) work.',
    tagline: 'Timeless beauty carved in wood.',
    price: 3200,
    currency: 'INR',
    category: 'Home Decor',
    stock: 15,
    images: ['/images/products/wood-carving.jpg'], // Local image
    isActive: true,
    status: 'active',
    createdAt: '2023-11-18T09:00:00Z',
    updatedAt: '2023-11-18T09:00:00Z',
    region: 'Uttar Pradesh',
    artisanName: 'Arjun Verma',
    aiInsights: {
      keyFeatures: ['Sheesham Wood', 'Hand-carved', 'Jaali Work'],
      styleTags: ['Rustic', 'Vintage', 'Heirloom'],
      useCases: ['Jewelry Box', 'Keepsake Storage', 'Gift Item'],
    },
  },
  {
    id: 'prod-22',
    name: 'Banarasi Silk Saree',
    artisanId: 'artisan-3',
    description: 'Regal, luxurious silk saree with gold zari work from the looms of Varanasi. A masterpiece of Indian weaving tradition.',
    tagline: 'The queen of sarees, straight from Varanasi.',
    price: 18000,
    currency: 'INR',
    category: 'Textiles',
    stock: 5,
    images: ['/images/products/banarasi-silk.jpg'], // Local image
    isActive: true,
    status: 'active',
    createdAt: '2023-11-19T10:00:00Z',
    updatedAt: '2023-11-19T10:00:00Z',
    region: 'Uttar Pradesh',
    artisanName: 'Arjun Verma',
    aiInsights: {
      keyFeatures: ['Pure Silk', 'Gold Zari', 'Handwoven'],
      styleTags: ['Royal', 'Wedding', 'Traditional'],
      useCases: ['Bridal Wear', 'Festive Occasions', 'Heirloom Collection'],
    },
  },
  {
    id: 'prod-23',
    name: 'Mathura Brass Chariot',
    artisanId: 'artisan-3',
    description: 'Detailed metal sculpting from Mathura. A handcrafted brass chariot featuring intricate figurines and traditional motifs, reflecting the city\'s heritage.',
    tagline: 'Timeless storytelling in brass.',
    price: 6500,
    currency: 'INR',
    category: 'Home Decor',
    stock: 6,
    images: ['/images/products/metal-sculpting.jpg'], // Local image
    isActive: true,
    status: 'active',
    createdAt: '2023-11-20T11:00:00Z',
    updatedAt: '2023-11-20T11:00:00Z',
    region: 'Uttar Pradesh',
    artisanName: 'Arjun Verma',
    aiInsights: {
      keyFeatures: ['Brass/Bronze', 'Lost Wax Casting', 'Religious Motif'],
      styleTags: ['Antique', 'Spiritual', 'Collectible'],
      useCases: ['Temple Decor', 'Console Table Display', 'Heritage Gift'],
    },
  },
  {
    id: 'prod-24',
    name: 'Khurja Ceramic Dinner Set',
    artisanId: 'artisan-3',
    description: 'A complete hand-painted ceramic dinner set from the Ceramic City, Khurja. Food safe and microwave friendly with vibrant traditional patterns.',
    tagline: 'Dine with the colors of tradition.',
    price: 5500,
    currency: 'INR',
    category: 'Kitchenware',
    stock: 10,
    images: ['/images/products/khurja-ceramics.jpg'], // Local image
    isActive: true,
    status: 'active',
    createdAt: '2023-11-21T09:30:00Z',
    updatedAt: '2023-11-21T09:30:00Z',
    region: 'Uttar Pradesh',
    artisanName: 'Arjun Verma',
    aiInsights: {
      keyFeatures: ['Bone China/Ceramic', 'Hand-Glazed', 'Durable'],
      styleTags: ['Floral', 'Bright', 'Family Dining'],
      useCases: ['Dinner Parties', 'Daily Use', 'Wedding Gift'],
    },
  },
  {
    id: 'prod-25',
    name: 'Mirzapur Handloom Dhurrie',
    artisanId: 'artisan-3',
    description: 'Durable and export-quality floor rug (dhurrie) woven in Mirzapur. Geometric patterns made from high-quality cotton yarn.',
    tagline: 'Rugged beauty for your floors.',
    price: 2400,
    currency: 'INR',
    category: 'Home Decor',
    stock: 30,
    images: ['/images/products/handloom-dhurries.jpg'], // Local image
    isActive: true,
    status: 'active',
    createdAt: '2023-11-22T14:15:00Z',
    updatedAt: '2023-11-22T14:15:00Z',
    region: 'Uttar Pradesh',
    artisanName: 'Arjun Verma',
    aiInsights: {
      keyFeatures: ['Flat Weave', 'Cotton/Wool', 'Reversible'],
      styleTags: ['Geometric', 'Boho', 'Modern Rustic'],
      useCases: ['Living Room Flooring', 'Outdoor Patio', 'Runner'],
    },
  },
  {
    id: 'prod-26',
    name: 'Bareilly Zardozi Wall Art',
    artisanId: 'artisan-3',
    description: 'Royal gold and silver threadwork (Zardozi) on velvet. This framed piece showcases the opulent embroidery style originally crafted for kings.',
    tagline: 'The royal touch of gold embroidery.',
    price: 7200,
    currency: 'INR',
    category: 'Home Decor',
    stock: 8,
    images: ['/images/products/zardozi-embroidery.jpg'], // Local image
    isActive: true,
    status: 'active',
    createdAt: '2023-11-23T10:00:00Z',
    updatedAt: '2023-11-23T10:00:00Z',
    region: 'Uttar Pradesh',
    artisanName: 'Arjun Verma',
    aiInsights: {
      keyFeatures: ['Gold/Silver Wire', 'Velvet Base', 'Hand Embroidered'],
      styleTags: ['Opulent', 'Regal', 'Ornate'],
      useCases: ['Wall Hanging', 'Luxury Gift', 'Drawing Room Decor'],
    },
  },
  {
    id: 'prod-27',
    name: 'Bhadohi Hand-Knotted Carpet',
    artisanId: 'artisan-3',
    description: 'A premium wool carpet from Bhadohi, the Carpet City of India. Densely knotted by hand for unmatched durability and intricate designs.',
    tagline: 'World-class luxury under your feet.',
    price: 25000,
    currency: 'INR',
    category: 'Home Decor',
    stock: 4,
    images: ['/images/products/bhadohi-carpets.jpg'], // Local image
    isActive: true,
    status: 'active',
    createdAt: '2023-11-24T12:00:00Z',
    updatedAt: '2023-11-24T12:00:00Z',
    region: 'Uttar Pradesh',
    artisanName: 'Arjun Verma',
    aiInsights: {
      keyFeatures: ['Persian Knot', 'Pure Wool', 'High Knot Count'],
      styleTags: ['Classic', 'Luxury', 'Grand Millennial'],
      useCases: ['Master Bedroom', 'Formal Living', 'Heirloom Investment'],
    },
  },
  {
    id: 'prod-28',
    name: 'Varanasi Silver Filigree Box',
    artisanId: 'artisan-3',
    description: 'Exquisite Silver Filigree (Tarkashi) work from Varanasi. This decorative box is made from twisted silver wire, forming delicate lace-like patterns.',
    tagline: 'Lace woven in silver.',
    price: 8500,
    currency: 'INR',
    category: 'Home Decor',
    stock: 7,
    images: ['/images/products/silver-filigree.jpg'], // Local image
    isActive: true,
    status: 'active',
    createdAt: '2023-11-25T14:30:00Z',
    updatedAt: '2023-11-25T14:30:00Z',
    region: 'Uttar Pradesh',
    artisanName: 'Arjun Verma',
    aiInsights: {
      keyFeatures: ['Pure Silver Wire', 'Tarkashi Art', 'Handcrafted'],
      styleTags: ['Delicate', 'Precious', 'Artistic'],
      useCases: ['Jewelry Storage', 'Gift for Her', 'Collectible'],
    },
  },
  {
    id: 'prod-29',
    name: 'Kanpur Leather Messenger Bag',
    artisanId: 'artisan-3',
    description: 'High-quality handcrafted leather messenger bag from Kanpur. Made from full-grain leather that ages beautifully, perfect for modern daily use.',
    tagline: 'Durability meets classic style.',
    price: 4800,
    currency: 'INR',
    category: 'Accessories',
    stock: 20,
    images: ['/images/products/leather-craft.jpg'], // Local image
    isActive: true,
    status: 'active',
    createdAt: '2023-11-26T10:00:00Z',
    updatedAt: '2023-11-26T10:00:00Z',
    region: 'Uttar Pradesh',
    artisanName: 'Arjun Verma',
    aiInsights: {
      keyFeatures: ['Full-Grain Leather', 'Hand-Stitched', 'Multiple Compartments'],
      styleTags: ['Vintage', 'Rugged', 'Professional'],
      useCases: ['Office Bag', 'Laptop Carrier', 'Travel Companion'],
    },
  },
];

export const orders: Order[] = [
  {
    id: 'ord-001',
    buyerId: 'user-123',
    artisanId: 'artisan-1',
    items: [{ productId: 'prod-1', productName: 'Azure Ceramic Vase', quantity: 1, unitPrice: 3750, itemImageUrl: 'https://picsum.photos/seed/prod1-1/600/600' }],
    totalAmount: 3750,
    shippingAddress: {
      fullName: "Alice Johnson",
      addressLine1: "123 Market St",
      city: "San Francisco",
      state: "CA",
      zipCode: "94103",
      country: "USA",
    },
    status: 'Delivered',
    paymentStatus: 'Paid',
    orderDate: '2023-10-15T10:30:00Z',
    updatedAt: '2023-10-20T15:00:00Z',
  },
  {
    id: 'ord-002',
    buyerId: 'user-456',
    artisanId: 'artisan-1',
    items: [
      { productId: 'prod-3', productName: 'Earthenware Mug Set', quantity: 1, unitPrice: 2500, itemImageUrl: 'https://picsum.photos/seed/prod3-1/600/600' },
      { productId: 'prod-4', productName: 'Geometric Print Scarf', quantity: 1, unitPrice: 2000, itemImageUrl: 'https://picsum.photos/seed/prod4-1/600/600' },
    ],
    totalAmount: 4500,
    shippingAddress: {
      fullName: "Bob Williams",
      addressLine1: "456 Oak Ave",
      city: "Chicago",
      state: "IL",
      zipCode: "60607",
      country: "USA"
    },
    status: 'Shipped',
    paymentStatus: 'Paid',
    orderDate: '2023-10-28T11:00:00Z',
    updatedAt: '2023-10-29T18:00:00Z',
  },
  {
    id: 'ord-003',
    buyerId: 'user-789',
    artisanId: 'artisan-2',
    items: [{ productId: 'prod-2', productName: 'Sunset Tapestry', quantity: 1, unitPrice: 9900, itemImageUrl: 'https://picsum.photos/seed/prod2-1/600/600' }],
    totalAmount: 9900,
    shippingAddress: {
      fullName: "Charlie Brown",
      addressLine1: "789 Pine Ln",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "USA"
    },
    status: 'Pending',
    paymentStatus: 'Pending Payment',
    orderDate: '2023-11-01T12:00:00Z',
    updatedAt: '2023-11-01T12:00:00Z',
  },
  {
    id: 'ord-004',
    buyerId: 'user-123',
    artisanId: 'artisan-2',
    items: [{ productId: 'prod-7', productName: 'Embroidered Cushion Cover', quantity: 2, unitPrice: 3200, itemImageUrl: 'https://images.unsplash.com/photo-1689413182146-14b0a9b972b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxN3x8ZW1icm9pZGVyZWQlMjBjdXNoaW9ufGVufDB8fHx8MTc1ODQ0NDc3Mnww&ixlib=rb-4.1.0&q=80&w=1080' }],
    totalAmount: 6400,
    shippingAddress: {
      fullName: "Alice Johnson",
      addressLine1: "123 Market St",
      city: "San Francisco",
      state: "CA",
      zipCode: "94103",
      country: "USA",
    },
    status: 'Processing',
    paymentStatus: 'Paid',
    orderDate: '2023-11-02T14:00:00Z',
    updatedAt: '2023-11-02T14:00:00Z',
  },
  {
    id: 'ord-005',
    buyerId: 'user-456',
    artisanId: 'artisan-1',
    items: [{ productId: 'prod-8', productName: 'Ceramic Tea Set', quantity: 1, unitPrice: 6800, itemImageUrl: 'https://picsum.photos/seed/prod8-1/600/600' }],
    totalAmount: 6800,
    shippingAddress: {
      fullName: "Bob Williams",
      addressLine1: "456 Oak Ave",
      city: "Chicago",
      state: "IL",
      zipCode: "60607",
      country: "USA"
    },
    status: 'Pending',
    paymentStatus: 'Pending Payment',
    orderDate: '2023-11-03T09:30:00Z',
    updatedAt: '2023-11-03T09:30:00Z',
  }
];

export const categories: string[] = [
  'Painting',
  'Jewelry',
  'Home Decor',
  'Textiles',
  'Kitchenware',
  'Accessories',
];

export const regions: string[] = [
  'Rajasthan',
  'Gujarat',
  'Uttar Pradesh',
  'Maharashtra',
  'West Bengal',
  'Tamil Nadu',
];





